[build.environment]
  NODE_VERSION = "14.15.0"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[context.production.environment]
  API_URL = "prod.url"

[context.branch-deploy.environment]
  API_URL = "dev.url"
